# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aNxzwCS6EUJICgIN5BTRjRgSbtVpuzZ
"""

import streamlit as st

st.title("🌈Emotion Upgraded Radar🌈")

gender = st.radio("Girl","Boy"),"Are You:"))
status = st.selectbox("Cold","Sad","Happy"),"What Do You Feel Now?"))

if st.button("Know Your Shape!")
 if status == "Happy":
   st.balloons()# Balloon Party!😁
   st.success("What A Good Day🌈")



  elif status == "Sad":
    st.info("Don't Be Sad Tommorow Will Be Better😊")

 elif status == "Cold":
   st.snow()#Magical Snow Effect